# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [5]:
A=np.zeros((10,10))
print("%d bytes" %(A.size*A.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [6]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [7]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [9]:
a=np.arange(0,10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [11]:
a=np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [13]:
print(np.random.random(27).reshape(3,3,3))

[[[0.75130068 0.97854508 0.72382641]
  [0.4599493  0.92237498 0.65358482]
  [0.08599162 0.04131201 0.31103331]]

 [[0.95693652 0.64610482 0.05073105]
  [0.16866071 0.26346009 0.71080285]
  [0.15782792 0.87198843 0.54401472]]

 [[0.88072446 0.32131464 0.29359516]
  [0.68013321 0.52867584 0.22839148]
  [0.37663091 0.36780192 0.6747491 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [14]:
a=np.random.random(100).reshape(10,10)
print("max",a.max())
print("min",a.min())

max 0.9920597188134105
min 0.009949922923984111


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [15]:
a=np.random.random(30)
print("mean",a.mean())

mean 0.571191108507593


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [16]:
a=np.ones(49).reshape(7,7)
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [17]:
a=np.arange(1,10)
print(np.pad(a,(1,1),'constant',constant_values=(0,0)))

[0 1 2 3 4 5 6 7 8 9 0]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [18]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)
"""
output is
nan
False
False
nan
False"""

nan
False
False
nan
False


'\noutput is\nnan\nFalse\nFalse\nnan\nFalse'

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [19]:
a=np.diag([1,2,3,4],k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [20]:
a=np.zeros(64).reshape(8,8)
a[::2,1::2]=1
a[1::2,::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [21]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [22]:
a=np.array([[0,1],[1,0]])
print(np.tile(a,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [23]:
a=np.arange(25).reshape(5,5)
b=(a-a.min())/(a.max()-a.min())
print(b)

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [24]:
np.dtype([('r',np.uint8),('g',np.uint8),('b',np.uint8),('a',np.uint8)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [25]:
a=np.arange(1,16).reshape(5,3)
b=np.arange(6).reshape(3,2)
a@b

array([[ 16,  22],
       [ 34,  49],
       [ 52,  76],
       [ 70, 103],
       [ 88, 130]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [26]:
a=np.arange(20)
a[(a>3) & (a<=7)]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
z=np.arange(10)
#below are expressions are legal except last one
print(z**z)      # z powerz    3 power 3 =27
print(z<-z)    #z< (-z)  condition false 2 <-2
print(1j*z)   #creating complex number arr
print(z/1/1)  #z converted to float
#not valid expessions
print(2 <<z >>2)  #not valid
#print(z<z>z)  #invalid  to conditions cannot be in one line

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[  0   1   2   4   8  16  32  64 128 256]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-29-6caa14b62dca>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0)/np.array(0))
<ipython-input-29-6caa14b62dca>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [30]:
a=np.random.uniform(-5,5,10)
print(np.copysign(np.ceil(np.abs(a)),a))

[ 3.  5.  1.  1. -2. -5. -1.  4. -2.  4.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [31]:
a=np.arange(3,10)
b=np.arange(5)
print(np.intersect1d(a,b))

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [32]:
#np.info(np.seterr)
#print(np.seterr(all="ignore"))
np.ones(3) /0
a=np.seterr(all="ignore")
print(np.seterr(**a))
with np.errstate(all='ignore'):
    print(np.sqrt(-2))

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}
nan


<ipython-input-32-3c6c373f5dd6>:3: RuntimeWarning: divide by zero encountered in true_divide
  np.ones(3) /0


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) #False  emath sqrt will return complex num 

False


<ipython-input-33-31448fde82b0>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) #False  emath sqrt will return complex num


33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [34]:
c=np.datetime64('today','D')-np.timedelta64(1,'D')
print("yesterday",b)
a=np.datetime64('today','D')
print("today",a)
c=np.datetime64('today','D')+np.timedelta64(1,'D')
print("tomorrow",c)

yesterday [0 1 2 3 4]
today 2023-01-13
tomorrow 2023-01-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [35]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [36]:
A=np.arange(9).reshape(3,3)
B=np.arange(9).reshape(3,3)
np.add(A,B,out=B)
np.divide(A,2,out=A,casting='unsafe')
np.negative(A,out=A)
print(np.multiply(A,B,out=A,casting='unsafe'))

[[  0   0  -4]
 [ -6 -16 -20]
 [-36 -42 -64]]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [37]:
a=np.random.uniform(0,10,10)
#print(a)
print(a-a%1)
print(np.floor(a))
print(np.ceil(a)-1)
print(a.astype(int))
print(np.trunc(a))

[8. 4. 6. 2. 5. 4. 5. 5. 9. 4.]
[8. 4. 6. 2. 5. 4. 5. 5. 9. 4.]
[8. 4. 6. 2. 5. 4. 5. 5. 9. 4.]
[8 4 6 2 5 4 5 5 9 4]
[8. 4. 6. 2. 5. 4. 5. 5. 9. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [38]:
a=np.tile(np.arange(5),(5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [39]:
iterator=(i for i in range(10))
print(np.fromiter(iterator,int))

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [40]:
np.linspace(0,1,endpoint=False)[1:]

array([0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 , 0.22,
       0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42, 0.44,
       0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64, 0.66,
       0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86, 0.88,
       0.9 , 0.92, 0.94, 0.96, 0.98])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [41]:
a=np.random.random(10)
a.sort()
print('after sorting',a)

after sorting [0.27309585 0.3073302  0.35989649 0.44933117 0.61841943 0.64488229
 0.7546819  0.8061352  0.86909962 0.92338892]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [42]:
A=np.arange(10)
print(np.add.reduce(A))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [43]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
#print(A)
#print(B)
print(np.allclose(A,B))  #with tolarance  assuming shape is same
print(np.array_equal(A,B))  #comparing shape and element wise without tolarance

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [44]:
A=np.ones(20)
A.flags.writeable=False     #read only
#A[0]=10

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [45]:
A=np.random.random((10,2))
X,Y=A[:,0],A[:,1]
R=np.sqrt(X**2+Y**2)   #radius
T=np.arctan2(Y,X)
print(R)
print(T)

[0.41845659 0.68531499 0.92164333 0.17090287 0.7578188  0.85685362
 0.68512982 1.2338868  0.209054   0.80216409]
[1.05062375 1.09786649 0.89284519 0.11654496 0.61080349 0.98728409
 1.24021079 0.82393415 1.39902226 0.78683949]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [46]:
a=np.random.randint(0,50,10)
#print(a)
#print(a.max())
a[a.argmax()]=0
print(a)

[ 0  7 18 43 21 19 15 13 40 31]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [47]:
A=np.zeros((5,5),[('x',float),('y',float)])
x=np.linspace(0,1,5)
y=np.linspace(0,1,5)
A['x'],A['y']=np.meshgrid(x,y)
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [48]:
X=np.arange(8)
Y=X+0.5
C=1/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [49]:
print("int")
for d_type in [np.int8,np.int32,np.int64]:
    print(np.iinfo(d_type).min)
    print(np.iinfo(d_type).max)
print("float")
for d_type in [np.float32, np.float64]:
    print(np.finfo(d_type).min)
    print(np.finfo(d_type).max)
    print(np.finfo(d_type).eps)

int
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
float
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. How to print all the values of an array? (★★☆) 
(**hint**: np.set_printoptions)

In [50]:
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.zeros((10, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [51]:
A= np.arange(100)
V=np.random.uniform(0,100)
i=(np.abs(A-V)).argmin()
print(A[i])

72


 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [52]:
a=np.dtype([('position',[('x',float,1),('y',float,1)]),
           ('color',[('r',float,1),('g',float,1),('b',float,1)]
          )])
print(np.zeros(20,a))

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-52-ccd27f365803>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a=np.dtype([('position',[('x',float,1),('y',float,1)]),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [53]:
a=np.random.random((100,2))
#print(a)
x,y=np.atleast_2d(a[:,0],a[:,1])
#print(x)
#print(y)
print(np.sqrt(((x-x.T)**2)+
              ((y-y.T)**2)))

[[0.         0.42804586 0.43266172 0.12747987 0.8374196  0.74695535
  0.37163783 0.79138776 0.64764825 0.0981061  0.40925097 0.92899117
  0.58167998 0.50516968 0.31261944 0.70139055 0.27470604 0.74833376
  0.61136579 0.72034789 0.34872851 0.60911073 0.57428659 0.31632722
  0.85002637 0.99657236 0.82562954 0.56309378 0.73215305 0.80842013
  0.02415646 0.88602051 0.88015448 0.27676551 0.62903761 0.74595995
  0.55384494 0.83351501 0.76111142 0.24982824 0.32758933 0.45293566
  0.70958376 0.63415515 0.25812933 0.73466481 0.61948465 0.37061454
  0.82153633 0.39681774 0.75387835 0.59752291 1.04256733 0.76440552
  0.94897633 0.19401069 0.49144037 0.76922732 0.35749286 0.78527687
  0.06928749 0.30106589 0.77495953 0.61756907 0.84509697 0.75413448
  0.96782925 0.96578934 0.41305488 0.85953314 0.21806878 0.56502812
  0.73147832 0.89958123 0.78836432 0.21041875 0.47824979 0.78215705
  1.03349597 0.25645069 0.30985936 0.73789167 0.84958049 0.2282933
  0.60235754 0.60886179 0.38793995 0.79539613 0.8

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [54]:
a=np.arange(10,dtype=np.float32)
print(a)
a=a.astype(dtype=np.int32,copy =False)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
from io import StringIO
s=StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
""")
a=np.genfromtxt(s,delimiter=",",dtype=np.int64)
a

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [56]:
a=np.arange(10).reshape(5,2)
print("np.denumerate")
for i,v in np.ndenumerate(a):
    print(i,"value",v)
print("np.index")
for i in np.ndindex(a.shape):
    print(i,"value",a[i])

np.denumerate
(0, 0) value 0
(0, 1) value 1
(1, 0) value 2
(1, 1) value 3
(2, 0) value 4
(2, 1) value 5
(3, 0) value 6
(3, 1) value 7
(4, 0) value 8
(4, 1) value 9
np.index
(0, 0) value 0
(0, 1) value 1
(1, 0) value 2
(1, 1) value 3
(2, 0) value 4
(2, 1) value 5
(3, 0) value 6
(3, 1) value 7
(4, 0) value 8
(4, 1) value 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [57]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma,mu=1,0
g=np.exp(-((d-mu)**2/(2*sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [58]:
num = 10
p = 3
a = np.zeros((num,num))
np.put(a, np.random.choice(range(num*num), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [59]:
a=np.random.randn(10,10)
b=a-np.mean(a,axis=1,keepdims=True)
print(b)

[[-0.6715245  -0.51771537  0.77023131  0.60219584  0.04423179  0.75893412
   0.50948576 -0.85679456 -0.6953262   0.05628181]
 [ 1.66495626 -1.04695959  1.44218264 -1.06994745  0.43011773 -0.47289668
   0.48938397 -0.37409792 -0.69839073 -0.36434825]
 [-0.88545777  0.03297277 -1.03588765 -0.0486974  -0.4121821   0.765926
   1.49371454 -0.3272534  -0.80917702  1.22604204]
 [ 0.60639589  0.05224036 -1.6608891   0.17390732  0.42539395 -0.27955882
   0.40858715 -0.18798792  1.25284291 -0.79093175]
 [-0.55766701  0.68328119  1.49300834  0.72049035 -1.8517122   1.01264693
  -1.50496493  0.45149141 -0.55692104  0.11034695]
 [-0.41395844  0.57546407 -1.56406653  0.82057963  0.02474214  0.27744171
  -0.69370401  0.77738862 -0.43117399  0.62728681]
 [-0.51515307 -0.04135825 -2.26615028  1.31419832 -0.92264118 -0.58133617
   0.82953024  0.45722508  0.86422428  0.86146104]
 [-1.93870366  0.43623307 -0.68475878  0.2488211  -0.87162026  2.97619682
   0.29453551 -0.75206103  0.04254856  0.24880867]
 [

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [60]:
a=np.random.randint(0,20,(5,5))
print(a)
n=1
print(a[a[:,n].argsort()])    # sorting column 1 wise all rows gets realigned based on col 1

[[ 2  0 16 17  1]
 [19  8  4 11 10]
 [ 5 11 10  2 18]
 [16  5  2 14 15]
 [ 6 10 18 15  6]]
[[ 2  0 16 17  1]
 [16  5  2 14 15]
 [19  8  4 11 10]
 [ 6 10 18 15  6]
 [ 5 11 10  2 18]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [61]:
a=np.random.randint(0,3,(3,10))
print((~a.any(axis=0).any()))        #will return true if all elements are 0's

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [62]:
a=np.random.uniform(0,1,10)
b=0.5
c=a.flat[np.abs(a-b).argmin()]
print(c)

0.45355898224818936


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [63]:
a=np.arange(3).reshape(1,3)
b=np.arange(5,8).reshape(3,1)
it=np.nditer([a,b,None])
for i,j,k in it:
    k[...]=i+j
print(it.operands[2])          #extracting K th storage

[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [64]:
class NamedArray(np.ndarray):
    def __new__(self,obj,name="no name"):
        self.name=name
        return self
z=NamedArray(np.arange(10),"abc")
print(z.name)

abc


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [65]:
a=np.ones(10)
I=np.random.randint(0,len(a),10)
a=a+np.bincount(I,minlength=len(a))
print(a)

[4. 2. 1. 2. 2. 1. 2. 2. 3. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [66]:
X=np.arange(5)
I=np.array([1,3,5,7,9])
F=np.bincount(I,X)
F

array([0., 0., 0., 1., 0., 2., 0., 3., 0., 4.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [67]:
w,h=16,16
a=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
b=a[...,0]*256*256+I[...,1]*256+I[...,2]
print(np.unique(I))

[1 3 5 7 9]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [68]:
a=np.arange(64).reshape(2,2,4,4)
#print(a)
print(a.sum(axis=(-2,-1)))

[[120 376]
 [632 888]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [69]:
D=np.random.uniform(0,1,20)
S=np.random.randint(0,10,20)
D_sum=np.bincount(S,weights=D)
D_count=np.bincount(S)
D_mean=D_sum/D_count
print(D_mean)

[       nan 0.64341318 0.59204812 0.43674746        nan 0.43650238
 0.6566995  0.24899866 0.91436718 0.3541572 ]


<ipython-input-69-1e17d20105f4>:5: RuntimeWarning: invalid value encountered in true_divide
  D_mean=D_sum/D_count


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [70]:
a=np.arange(25).reshape(5,5)
b=np.arange(25,50).reshape(5,5)
dot_p=np.dot(a,b)
#print(dot_p)
print(np.diag(dot_p))

[ 400 1310 2270 3280 4340]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [71]:
a=np.array([1,2,3,4,5])
no_of_zeros=3
#print(a)
no_of_zeros_to_be_added=no_of_zeros*(len(a)-1)
b=np.zeros(len(a)+no_of_zeros_to_be_added)
#print(b)
b[::no_of_zeros+1]=a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [72]:
a=np.arange(75).reshape(5,5,3)
b=np.arange(25).reshape(5,5)
print(a*b[:,:,None])

[[[   0    0    0]
  [   3    4    5]
  [  12   14   16]
  [  27   30   33]
  [  48   52   56]]

 [[  75   80   85]
  [ 108  114  120]
  [ 147  154  161]
  [ 192  200  208]
  [ 243  252  261]]

 [[ 300  310  320]
  [ 363  374  385]
  [ 432  444  456]
  [ 507  520  533]
  [ 588  602  616]]

 [[ 675  690  705]
  [ 768  784  800]
  [ 867  884  901]
  [ 972  990 1008]
  [1083 1102 1121]]

 [[1200 1220 1240]
  [1323 1344 1365]
  [1452 1474 1496]
  [1587 1610 1633]
  [1728 1752 1776]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [73]:
A=np.arange(25).reshape(5,5)
#print(A)
A[[0,4]] = A[[4,0]]
print(A)

[[20 21 22 23 24]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [74]:
f=np.random.randint(0,100,(10,3))
c=f.repeat(2,axis=1)   #twice each columns are repeated
F=np.roll(c,-1,axis=1)  #shift column wise
F=F.reshape(len(F)*3,2)    #reshaping matrix to (30,2)
F=np.sort(F,axis=1)
G=F.view(dtype=[('p0',f.dtype),('p1',f.dtype)])
print(np.unique(G))

[( 1, 76) ( 1, 90) ( 4, 13) ( 4, 52) (11, 72) (11, 85) (13, 17) (13, 30)
 (13, 52) (15, 70) (15, 81) (17, 30) (22, 33) (22, 75) (31, 37) (31, 95)
 (33, 75) (37, 74) (37, 88) (37, 95) (39, 52) (39, 79) (52, 79) (60, 80)
 (60, 91) (70, 81) (72, 85) (74, 88) (76, 90) (80, 91)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [75]:
C=np.bincount([1,1,2,3,4,4,6])
print(C)
A=np.repeat(np.arange(len(C)),C)
print(A)
#print(np.bincount(A))

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [76]:
def moving_avg(a,n):
    r=np.cumsum(a,dtype=float)
    r[n:]=r[n:]-r[:-n]
    return r[n-1:]/n    
a=np.arange(20)
r=moving_avg(a,3)
print(r)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [77]:
from numpy.lib import stride_tricks
def rolling(a,n):
    shape=(a.size-n+1,n)
    strides=(a.itemsize,a.itemsize)
    return stride_tricks.as_strided(a,shape=shape,strides=strides)
r=rolling(np.arange(10),3)
print(r)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [78]:
a=np.random.randint(0,20,10)
print(np.logical_not(a))
b=np.random.uniform(-1,1,10)
print(np.negative(b))

[False False False False  True False False False False False]
[-0.38544282 -0.88462543  0.94537052  0.71409968 -0.35090952 -0.58370048
 -0.40994885  0.60304781  0.32360784 -0.15383855]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [79]:
def distance(P0,P1,p):
    T=P1-P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-p[...,0])*T[:,0]+(P1[:,1]-p[...,1])*T[:,1])/L
    U=U.reshape(len(U),1)
    D=P0+U*T-p
    return np.sqrt((D**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2))
print(distance(P0,P1,p))

[4.46053671 6.64721308 8.30309418 3.3291334  5.34611943 5.80302597
 4.2258375  2.42885176 6.67766157 3.69625694]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [80]:
def distance(P0,P1,p):
    T=P1-P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-p[...,0])*T[:,0]+(P1[:,1]-p[...,1])*T[:,1])/L
    U=U.reshape(len(U),1)
    D=P0+U*T-p
    return np.sqrt((D**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.42467492  9.93157122 19.32490491  8.23161089  9.21124047 12.20618462
  11.97447737 13.8999228   5.95819904  3.63570542]
 [ 3.98749028 11.01958984 11.66739038  7.81669757  5.65124594  7.43800864
  14.90091752 12.24589613  1.89787764  5.90898238]
 [ 1.85895704  8.54515745 14.38956271  6.14516239  5.05646875  8.55444128
  12.08050227 11.39899569  4.20504835  2.30619862]
 [11.51878639  8.80512616 12.56441275 11.34453132  8.41548807  9.19890903
  12.6793423  12.30141952 11.55090103  3.63467513]
 [ 4.16037222  8.50095587 14.23022475  6.65825702  4.7507879   7.65096756
  12.01187999 11.33754764  6.76478701  2.13576557]
 [ 3.63530721 11.2245013  21.0359878   8.95401853 10.25963063 12.87899643
  12.69660852 15.0079667   7.49037535  5.43913476]
 [ 4.04393527  9.60449129 17.67941636  6.15051087  5.26981456  8.1941056
  11.76670428 12.1185139  10.89328303  6.23531405]
 [12.1935125  10.13834759 11.56231445 12.88067574 10.13665101 10.16485849
  14.25439545 13.61297621  9.58234497  2.02678497]
 

 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [81]:
import numpy as np
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R= Z[z[0]]
print(Z)
print(R)

[[7 1 2 9 4 7 9 3 3 4]
 [6 1 5 6 4 1 9 3 5 3]
 [0 1 9 1 4 5 6 0 9 7]
 [4 4 3 6 1 8 4 2 5 2]
 [3 9 6 4 3 2 4 6 5 0]
 [8 3 2 2 9 7 3 5 7 8]
 [2 0 2 3 4 3 1 7 8 6]
 [2 5 4 7 7 1 1 3 1 0]
 [3 3 7 1 4 8 0 8 6 2]
 [2 0 0 7 3 3 5 5 2 4]]
[[7 1 2 9 4 7 9 3 3 4]
 [6 1 5 6 4 1 9 3 5 3]
 [0 1 9 1 4 5 6 0 9 7]
 [4 4 3 6 1 8 4 2 5 2]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [82]:
from numpy.lib import stride_tricks
a=np.arange(1,15,dtype=np.uint32)
#print(a)
b=stride_tricks.as_strided(a,(11,4),(4,4))
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [83]:
a=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(a)
rank=np.sum(S>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [84]:
a=np.array([1,2,2,3,3,4,3,4,5,5,5,5,5,5,7])
b=np.bincount(a)
print(np.argmax(b))

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [85]:
a=np.random.randint(0,5,(10,10))
n=3
i=1+(a.shape[0]-3)
j=1+(a.shape[1]-3)
C=stride_tricks.as_strided(a,shape=(i,j,n,n),strides=a.strides+a.strides)
print(C)

[[[[0 2 1]
   [1 0 4]
   [1 2 4]]

  [[2 1 4]
   [0 4 1]
   [2 4 0]]

  [[1 4 2]
   [4 1 0]
   [4 0 3]]

  [[4 2 1]
   [1 0 1]
   [0 3 3]]

  [[2 1 4]
   [0 1 4]
   [3 3 3]]

  [[1 4 0]
   [1 4 2]
   [3 3 3]]

  [[4 0 1]
   [4 2 1]
   [3 3 3]]

  [[0 1 3]
   [2 1 4]
   [3 3 3]]]


 [[[1 0 4]
   [1 2 4]
   [4 4 4]]

  [[0 4 1]
   [2 4 0]
   [4 4 0]]

  [[4 1 0]
   [4 0 3]
   [4 0 3]]

  [[1 0 1]
   [0 3 3]
   [0 3 0]]

  [[0 1 4]
   [3 3 3]
   [3 0 2]]

  [[1 4 2]
   [3 3 3]
   [0 2 1]]

  [[4 2 1]
   [3 3 3]
   [2 1 1]]

  [[2 1 4]
   [3 3 3]
   [1 1 0]]]


 [[[1 2 4]
   [4 4 4]
   [1 4 4]]

  [[2 4 0]
   [4 4 0]
   [4 4 2]]

  [[4 0 3]
   [4 0 3]
   [4 2 0]]

  [[0 3 3]
   [0 3 0]
   [2 0 2]]

  [[3 3 3]
   [3 0 2]
   [0 2 2]]

  [[3 3 3]
   [0 2 1]
   [2 2 4]]

  [[3 3 3]
   [2 1 1]
   [2 4 0]]

  [[3 3 3]
   [1 1 0]
   [4 0 1]]]


 [[[4 4 4]
   [1 4 4]
   [2 1 2]]

  [[4 4 0]
   [4 4 2]
   [1 2 4]]

  [[4 0 3]
   [4 2 0]
   [2 4 2]]

  [[0 3 0]
   [2 0 2]
   [4 2 3]]

  [[3 0 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [86]:
class Symetric(np.ndarray):
    def __setitem__(self,index,value):
        i,j=index
        super(Symetric,self).__setitem__((i,j),value)
        super(Symetric,self).__setitem__((j,i),value)
def symetric(a):
    return np.asarray(a+a.T-np.diag(a.diagonal())).view(Symetric)
S=symetric(np.random.randint(0,10,(5,5)))
S[2,3]=42
print(S)

[[ 8 16  6  5 11]
 [16  7 15  3  7]
 [ 6 15  1 42 12]
 [ 5  3 42  4  7]
 [11  7 12  7  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [87]:
p,n=10,20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [88]:
a=np.ones((16,16))
k=4
b=np.add.reduceat(np.add.reduceat(a,np.arange(0,a.shape[0],k),axis=0),
                                np.arange(0,a.shape[1],k),axis=1)
print(b)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [89]:
def iterated(a):
    N = (a[0:-2,0:-2] + a[0:-2,1:-1] + a[0:-2,2:] +
         a[1:-1,0:-2]                + a[1:-1,2:] +
         a[2:  ,0:-2] + a[2:  ,1:-1] + a[2:  ,2:])
    birth = (N==3) & (a[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (a[1:-1,1:-1]==1)
    a[...] = 0
    a[1:-1,1:-1][birth | survive] = 1
    return a
a= np.random.randint(0,2,(50,50))
for i in range(100):
    a = iterated(a)
print(a)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [90]:
a=np.arange(10000)
n=5
print(a[np.argsort(a)[-n:]])
print(a[np.argpartition(-a,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9999 9998 9997 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [91]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]  #converting array to numpy arr
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)    #making indices array with idx representation
    ix = ix.reshape(len(arrays), -1).T        #consolidating and taking transpose
    for n, arr in enumerate(arrays):        #seperating iterators and arrays 
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [92]:
a=np.array([("hello",3.7,6.5),("world",7,4.9)])
r=np.core.records.fromarrays(a.T,names=('a','b','c'))    # passing three arrays by transpose and getting core dump 
print(r)

[('hello', '3.7', '6.5') ('world', '7', '4.9')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [93]:
Z=np.arange(5)
print(np.power(Z,3))
print(Z*Z*Z)
print(np.einsum('i,i,i->i',Z,Z,Z))

[ 0  1  8 27 64]
[ 0  1  8 27 64]
[ 0  1  8 27 64]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [94]:
a=np.random.randint(0,5,(8,3))
b=np.random.randint(0,5,(2,2))
c=(a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [95]:
A= np.random.randint(0,5,(10,3))
print(A)
E = np.all(A[:,1:] == A[:,:-1], axis=1)
U = A[~E]
print(U)

[[0 0 3]
 [1 1 0]
 [0 1 1]
 [0 0 1]
 [1 2 3]
 [2 1 1]
 [0 4 2]
 [1 3 0]
 [4 0 3]
 [0 3 4]]
[[0 0 3]
 [1 1 0]
 [0 1 1]
 [0 0 1]
 [1 2 3]
 [2 1 1]
 [0 4 2]
 [1 3 0]
 [4 0 3]
 [0 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [96]:
a=np.array([1,2,3,4,5,8],dtype=np.uint8)
print(np.unpackbits(a[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 1 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [97]:
A= np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(A).view(np.dtype((np.void, A.dtype.itemsize * A.shape[1])))
_, idx = np.unique(T, return_index=True)
uA = A[idx]
print(uA)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [98]:
A = np.array([1,2,3,4,5])
B = np.array([10,20,30,40,50])
print(np.einsum('i->', A))       #sum
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j->ij', A, B))    # np.outer(A, B)

15
[ 10  40  90 160 250]
550
[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]
 [ 50 100 150 200 250]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [99]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate_path
r_int = np.linspace(0, r.max(), 200) # regular_spaced_path
x_int = np.interp(r_int, r, x)       # integrate_path
y_int = np.interp(r_int, r, y)
#print(x_int)
#print(y_int)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [100]:
A = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(A, 1) == 0, axis=-1)
M &= (A.sum(axis=-1) == n)
print(A[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [101]:
A = np.random.randn(100) # random 1D array
N = 1000 # no.of bootstrap samples
idx = np.random.randint(0, A.size, (N, A.size))
means = A[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21078288  0.11534017]
